name: "Automerge"

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
    - name: Automerge
      uses: pascalgn/automerge-action@v0.14.3
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "!work in progress"
        MERGE_METHOD: "merge"
        MERGE_COMMIT_MESSAGE: "pull-request-title"
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "10000"
